### ISSUE TITLE
Python environment for learners

### ISSUE THREAD

**Issue by dtxe** [UofT-DSI/Onboarding#2]
Moving the Python discussion here. Related to #3.

Suggestion is to move to Local installation, with GitHub Codespaces as a backup.

# Options for learning environments
## Colab
* Current environment
* No proper way to use the shell / git / python cli
* No cost to learner
* Rare cases of learners getting pre-empted and losing connectivity during class
* Google account required

## Local installation
* Automated installation script will work for most learners
* Potential for incompatibility with learner's computer and OS/software environment
* Learners have fully functioning dev environment during and after the course

## GitHub Codespaces
* Requires a base Git repository
* Need to introduce the concept of GitHub and Git repositories earlier than current curriculum
* Only 60 hours free per month
* Learners have a fully functioning, but non-native dev environment
* GitHub account required (but also required for other parts of the course)

**Comment by danielrazavi** [comment]
New environment update: 
We will now start stepping away from google colab and use Python, git and shell (git bash for windows) locally on learners' personal computers.
